# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsr_agent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64sr_agent.proto\x12\tdsr_agent\"\x1c\n\x0c\x41gentMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bServerReply\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\x05\x41gent\x12\x45\n\x10SendAgentMessage\x12\x17.dsr_agent.AgentMessage\x1a\x16.dsr_agent.ServerReply\"\x00\x42\x15\x42\x13\x44\x61taSpireAgentProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dsr_agent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\023DataSpireAgentProto'
  _AGENTMESSAGE._serialized_start=30
  _AGENTMESSAGE._serialized_end=58
  _SERVERREPLY._serialized_start=60
  _SERVERREPLY._serialized_end=90
  _AGENT._serialized_start=92
  _AGENT._serialized_end=170
# @@protoc_insertion_point(module_scope)
