// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: dsr_agent/dsr_agent.proto

package dsr_agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DsrAgentClient is the client API for DsrAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DsrAgentClient interface {
	// Sends a message
	SendMessage(ctx context.Context, in *GRPCMessagePackage, opts ...grpc.CallOption) (*ServerReply, error)
}

type dsrAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewDsrAgentClient(cc grpc.ClientConnInterface) DsrAgentClient {
	return &dsrAgentClient{cc}
}

func (c *dsrAgentClient) SendMessage(ctx context.Context, in *GRPCMessagePackage, opts ...grpc.CallOption) (*ServerReply, error) {
	out := new(ServerReply)
	err := c.cc.Invoke(ctx, "/dsr_agent.DsrAgent/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DsrAgentServer is the server API for DsrAgent service.
// All implementations must embed UnimplementedDsrAgentServer
// for forward compatibility
type DsrAgentServer interface {
	// Sends a message
	SendMessage(context.Context, *GRPCMessagePackage) (*ServerReply, error)
	mustEmbedUnimplementedDsrAgentServer()
}

// UnimplementedDsrAgentServer must be embedded to have forward compatible implementations.
type UnimplementedDsrAgentServer struct {
}

func (UnimplementedDsrAgentServer) SendMessage(context.Context, *GRPCMessagePackage) (*ServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedDsrAgentServer) mustEmbedUnimplementedDsrAgentServer() {}

// UnsafeDsrAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DsrAgentServer will
// result in compilation errors.
type UnsafeDsrAgentServer interface {
	mustEmbedUnimplementedDsrAgentServer()
}

func RegisterDsrAgentServer(s grpc.ServiceRegistrar, srv DsrAgentServer) {
	s.RegisterService(&DsrAgent_ServiceDesc, srv)
}

func _DsrAgent_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCMessagePackage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DsrAgentServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsr_agent.DsrAgent/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DsrAgentServer).SendMessage(ctx, req.(*GRPCMessagePackage))
	}
	return interceptor(ctx, in, info, handler)
}

// DsrAgent_ServiceDesc is the grpc.ServiceDesc for DsrAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DsrAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsr_agent.DsrAgent",
	HandlerType: (*DsrAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _DsrAgent_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsr_agent/dsr_agent.proto",
}
